[project]
name = "modelbuilder"
channels = ["conda-forge"]
platforms = ["win-64"]

[environments]
modelbuilder = { features = ["default"] }

[dependencies]
geopandas ="==0.14.1"
pandas = "==2.0.2" 
python = "==3.9.18"
gdal = "==3.8.5"
pip = "==24.0"
rasterio = ">=1.3.9"
fiona = "==1.9.5"
shapely = "==2.0.4"
pyogrio = "==0.7.2"
rtree = "==1.0.1"
postgresql="==16.7"
scipy = "==1.10.1"
dask = "==2024.6.2"
rioxarray = "==0.15.0"
xarray = "==2024.3.0"
tqdm= "==4.64.0"

# HHNK deps
lazy-loader = "*"

# Datachecker
flask = "*"  # oude datachecker
sqlparse = "*"  # oude datachecker
psycopg2 = "*"  # oude datachecker
fastapi = "*"  # nieuwe datachecker
uvicorn = "*"  # nieuwe datachecker
django = "<4"  # datachecker (<4 wegens compatibility met 3Di modules)


[pypi-dependencies]
hhnk-research-tools = { path = "D:/github/jacosta/hhnk-research-tools", editable = true }
# threedi-api-client = "==4.1.7"
threedi-modelchecker = "==2.6.3"
threedi-scenario-downloader = "==1.4"
threedi-schema = "==0.219.3"
threedigrid = "==2.3.3"
threedigrid-builder = "==1.14.4"
threedidepth = "==0.6.3"